shell部分接近尾声

diff --git a/sys_info_page b/sys_info_page
--- a/sys_info_page
+++ b/sys_info_page
@@ -2,6 +2,7 @@
 
 #输出系统信息的页面
 
+PROGNAME=$(basename $0)
 TITLE="System Information $HOSTNAME"
 CURRENT_TIME=$(date +"%x %r %Z")
 TIME_STAMP="Generated $CURRENT_TIME, by $USER"
@@ -35,6 +36,12 @@ report_home_space(){
 	return
 }
 
+usage() {
+	echo "$PROGNAME: usage: $PROGNAME [-f file | -i]"
+	return
+}
+
+write_html_page(){
 cat << _EOF_
 <HTML>
 	<HEAD>
@@ -49,3 +56,58 @@ cat << _EOF_
 	</BODY>
 </HTML>
 _EOF_
+}
+
+#process command line options
+
+interactive=
+filename=
+while [[ -n $1 ]]; do
+	case $1 in
+		-f | --file)	shift
+				filename=$1
+				;;
+		-i | --interactive)	interactive=1
+					;;
+		-h | --help)	usage
+				exit
+				;;
+		*)	usage >&2
+			exit 1
+			;;
+	esac
+	shift
+done
+
+#interactive mode
+if [[ -n $interactive ]]; then
+	while true; do
+		read -p "Enter name of output file:" filename
+		if [[ -e $filename ]]; then
+			read -p "'$filename' exists.Overwrite?[y/n/q] >"
+			case $REPLY in
+				Y|y) break
+					;;
+				Q|q) echo "Program ternimated"
+					exit
+					;;
+				*) continue
+					;;
+			esac
+		fi
+	done
+fi
+
+# output html page
+if [[ -n $%filename ]]; then
+	if touch $filename && [[ -f $filename ]]; then
+		write_html_page > $filename
+	else
+		echo "$PROGNAME: Cannot write file '$filename' " >&2
+		exit 1
+	fi
+else
+	write_html_page
+fi
+
+
